name: CheckReleaseBinary
on:
  workflow_call:
    inputs:
      override_git_describe:
        type: string
        required: true
      git_ref:
        type: string
      prev_version:
        type: string
        default: v1.2.0
      current_hash:
        type: string
  workflow_dispatch:
    inputs:
      override_git_describe:
        type: string
        description: 'The version to be released (e.g. v1.2.0)'
        required: true
      git_ref:
        type: string
        description: 'The git ref to check out'
      prev_version:
        type: string
        description: 'The previous version to test against for compatibility'
        default: v1.2.0
      current_hash:
        type: string
        description: 'The hash of the version to be released'

concurrency:
  group: checkreleasebinary-${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}-${{ inputs.override_git_describe }}-${{ inputs.git_ref }}
  cancel-in-progress: true

jobs:
  check-release-binary:
    name: Check Release Binary (${{ matrix.config.arch }})
    runs-on: ${{ matrix.config.runner }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { runner: ubuntu-latest, arch: linux-amd64, extension_platform: linux_amd64 }
          - { runner: ubuntu-24.04-arm, arch: linux-arm64, extension_platform: linux_arm64 }
          - { runner: macos-latest, arch: osx-universal, extension_platform: osx_arm64 }
          - { runner: windows-latest, arch: windows-amd64, extension_platform: windows_amd64 }
          - { runner: windows-latest, arch: windows-arm64, extension_platform: windows-arm64}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run Check Release Binary
        shell: bash
        run: |
          bash scripts/check_release_binary.sh \
            --prev-version "${{ inputs.prev_version }}" \
            --current-version "${{ inputs.override_git_describe }}" \
            --current-hash "${{ inputs.current_hash }}" \
            --platform "${{ matrix.config.extension_platform }}"
